"""
    Bundestag: Lobbyregister

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.3
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from deutschland.bundestag_lobbyregister.exceptions import ApiAttributeError
from deutschland.bundestag_lobbyregister.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    OpenApiModel,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)


class Activity(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ("code",): {
            "CONSULTING": "ACT_CONSULTING",
            "EMPLOYEE_ASSOC": "ACT_EMPLOYEE_ASSOC",
            "EMPLOYER_ASSOC": "ACT_EMPLOYER_ASSOC",
            "LAWYER": "ACT_LAWYER",
            "NONPROFIT_ORGA": "ACT_NONPROFIT_ORGA",
            "ORGANIZATION": "ACT_ORGANIZATION",
            "OTHER": "ACT_OTHER",
            "PRIVATE": "ACT_PRIVATE",
            "PRIVATE_ORGA": "ACT_PRIVATE_ORGA",
            "PROFESSION_ASSOC": "ACT_PROFESSION_ASSOC",
            "PUBLIC_LAW_ORGA": "ACT_PUBLIC_LAW_ORGA",
            "RELIGIOUS_GROUP": "ACT_RELIGIOUS_GROUP",
            "RESEARCH_FACILITY": "ACT_RESEARCH_FACILITY",
            "TRADE_ASSOC": "ACT_TRADE_ASSOC",
        },
        ("de",): {
            "BERATUNGSUNTERNEHMEN,_SELBSTÄNDIGE_BERATERIN_ODER_SELBSTÄNDIGER_BERATER": "Beratungsunternehmen, selbständige Beraterin oder selbständiger Berater",
            "ARBEITNEHMERVERBAND": "Arbeitnehmerverband",
            "ARBEITGEBERVERBAND": "Arbeitgeberverband",
            "ANWALTSKANZLEI,_EINZELANWÄLTIN_ODER_EINZELANWALT": "Anwaltskanzlei, Einzelanwältin oder Einzelanwalt",
            "NICHTSTAATLICHE_ORGANISATION_(NICHTREGIERUNGSORGANISATION,_PLATTFORM_ODER_NETZWERK)": "Nichtstaatliche Organisation (Nichtregierungsorganisation, Plattform oder Netzwerk)",
            "UNTERNEHMEN": "Unternehmen",
            "PRIVATPERSON": "Privatperson",
            "PRIVATRECHTLICHE_ORGANISATION_MIT_GEMEINWOHLAUFGABEN_(Z. B._EINGETRAGENE_VEREINE,_STIFTUNGEN)": "Privatrechtliche Organisation mit Gemeinwohlaufgaben (z. B. eingetragene Vereine, Stiftungen)",
            "BERUFSVERBAND": "Berufsverband",
            "ÖFFENTLICH-RECHTLICHE_ORGANISATION_(Z._B._KÖRPERSCHAFTEN,_ANSTALTEN_UND_STIFTUNGEN_DES_ÖFFENTLICHEN_RECHTS)": "Öffentlich-rechtliche Organisation (z. B. Körperschaften, Anstalten und Stiftungen des öffentlichen Rechts)",
            "KIRCHE_ODER_ANDERE_RELIGIONS-_ODER_WELTANSCHAUUNGSGEMEINSCHAFT": "Kirche oder andere Religions- oder Weltanschauungsgemeinschaft",
            "DENKFABRIK,_FORSCHUNGSEINRICHTUNG_ODER_HOCHSCHULE": "Denkfabrik, Forschungseinrichtung oder Hochschule",
            "WIRTSCHAFTSVERBAND_ODER_GEWERBEVERBAND/-VEREIN": "Wirtschaftsverband oder Gewerbeverband/-verein",
        },
        ("en",): {
            "CONSULTING_COMPANY,_INDEPENDENT_CONSULTANT": "Consulting company, independent consultant",
            "WORKERS_ASSOCIATION": "Workers association",
            "EMPLOYERS_ASSOCIATION": "Employers association",
            "LAW_FIRM,_INDIVIDUAL_ATTORNEY": "Law firm, individual attorney",
            "NON-GOVERNMENTAL_ORGANIZATIONS_(NON-GOVERNMENTAL_ORGANIZATION,_PLATFORM_OR_NETWORK)": "Non-governmental organizations (non-governmental organization, platform or network)",
            "COMPANY": "Company",
            "PRIVATE_CITIZEN": "Private citizen",
            "ORGANIZATION_UNDER_PRIVATE_LAW_WITH_PUBLIC_WELFARE_TASKS_(E.G._REGISTERED_ASSOCIATIONS,_FOUNDATIONS)": "Organization under private law with public welfare tasks (e.g. registered associations, foundations)",
            "PROFESSIONAL_ASSOCIATION": "Professional association",
            "PUBLIC_LAW_ORGANIZATION_(E.G._CORPORATIONS,_INSTITUTIONS_AND_FOUNDATIONS_UNDER_PUBLIC_LAW)": "Public law organization (e.g. corporations, institutions and foundations under public law)",
            "CHURCH_OR_OTHER_RELIGIOUS_OR_IDEOLOGICAL_COMMUNITY": "Church or other religious or ideological community",
            "THINK_TANK,_RESEARCH_INSTITUTION_OR_UNIVERSITY": "Think tank, research institution or university",
            "TRADE_ASSOCIATION": "Trade association",
        },
    }

    validations = {}

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        return (
            bool,
            date,
            datetime,
            dict,
            float,
            int,
            list,
            str,
            none_type,
        )  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        return {
            "code": (str,),  # noqa: E501
            "de": (str,),  # noqa: E501
            "en": (str,),  # noqa: E501
            "text": (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None

    attribute_map = {
        "code": "code",  # noqa: E501
        "de": "de",  # noqa: E501
        "en": "en",  # noqa: E501
        "text": "text",  # noqa: E501
    }

    read_only_vars = {}

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, code, *args, **kwargs):  # noqa: E501
        """Activity - a model defined in OpenAPI

        Args:
            code (str):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            de (str): [optional]  # noqa: E501
            en (str): [optional]  # noqa: E501
            text (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop("_check_type", True)
        _spec_property_naming = kwargs.pop("_spec_property_naming", False)
        _path_to_item = kwargs.pop("_path_to_item", ())
        _configuration = kwargs.pop("_configuration", None)
        _visited_composed_classes = kwargs.pop("_visited_composed_classes", ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments."
                % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.code = code
        for var_name, var_value in kwargs.items():
            if (
                var_name not in self.attribute_map
                and self._configuration is not None
                and self._configuration.discard_unknown_keys
                and self.additional_properties_type is None
            ):
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set(
        [
            "_data_store",
            "_check_type",
            "_spec_property_naming",
            "_path_to_item",
            "_configuration",
            "_visited_composed_classes",
        ]
    )

    @convert_js_args_to_python_args
    def __init__(self, code, *args, **kwargs):  # noqa: E501
        """Activity - a model defined in OpenAPI

        Args:
            code (str):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            de (str): [optional]  # noqa: E501
            en (str): [optional]  # noqa: E501
            text (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop("_check_type", True)
        _spec_property_naming = kwargs.pop("_spec_property_naming", False)
        _path_to_item = kwargs.pop("_path_to_item", ())
        _configuration = kwargs.pop("_configuration", None)
        _visited_composed_classes = kwargs.pop("_visited_composed_classes", ())

        if args:
            raise ApiTypeError(
                "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments."
                % (
                    args,
                    self.__class__.__name__,
                ),
                path_to_item=_path_to_item,
                valid_classes=(self.__class__,),
            )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.code = code
        for var_name, var_value in kwargs.items():
            if (
                var_name not in self.attribute_map
                and self._configuration is not None
                and self._configuration.discard_unknown_keys
                and self.additional_properties_type is None
            ):
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(
                    f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                    f"class with read only attributes."
                )
