"""
    Bundestag: Lobbyregister API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.3
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from deutschland.bundestag_lobbyregister.exceptions import ApiAttributeError
from deutschland.bundestag_lobbyregister.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    OpenApiModel,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
)


def lazy_import():
    from deutschland.bundestag_lobbyregister.model.activity import Activity
    from deutschland.bundestag_lobbyregister.model.client_organization import (
        ClientOrganization,
    )
    from deutschland.bundestag_lobbyregister.model.donator import Donator
    from deutschland.bundestag_lobbyregister.model.entry_account import EntryAccount
    from deutschland.bundestag_lobbyregister.model.entry_employee_count import (
        EntryEmployeeCount,
    )
    from deutschland.bundestag_lobbyregister.model.entry_financial_expenses_euro import (
        EntryFinancialExpensesEuro,
    )
    from deutschland.bundestag_lobbyregister.model.field_of_interest import (
        FieldOfInterest,
    )
    from deutschland.bundestag_lobbyregister.model.legislative_project import (
        LegislativeProject,
    )
    from deutschland.bundestag_lobbyregister.model.lobbyist_identity import (
        LobbyistIdentity,
    )
    from deutschland.bundestag_lobbyregister.model.media import Media
    from deutschland.bundestag_lobbyregister.model.named_employee import NamedEmployee

    globals()["Activity"] = Activity
    globals()["ClientOrganization"] = ClientOrganization
    globals()["Donator"] = Donator
    globals()["EntryAccount"] = EntryAccount
    globals()["EntryEmployeeCount"] = EntryEmployeeCount
    globals()["EntryFinancialExpensesEuro"] = EntryFinancialExpensesEuro
    globals()["FieldOfInterest"] = FieldOfInterest
    globals()["LegislativeProject"] = LegislativeProject
    globals()["LobbyistIdentity"] = LobbyistIdentity
    globals()["Media"] = Media
    globals()["NamedEmployee"] = NamedEmployee


class Entry(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ("client_identity",): {
            "BOTH": "BOTH",
            "NATURAL_PERSON": "NATURAL_PERSON",
            "ORGANIZATION": "ORGANIZATION",
            "-": "-",
        },
        ("activity_operation_type",): {
            "BOTH": "BOTH",
            "SELF_OPERATED": "SELF_OPERATED",
            "MANDATE_OPERATED": "MANDATE_OPERATED",
        },
    }

    validations = {}

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (
            bool,
            date,
            datetime,
            dict,
            float,
            int,
            list,
            str,
            none_type,
        )  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            "id": (int,),  # noqa: E501
            "client_identity": (str,),  # noqa: E501
            "employee_count": (EntryEmployeeCount,),  # noqa: E501
            "refuse_financial_expenses_information": (bool,),  # noqa: E501
            "financial_expenses_euro": (EntryFinancialExpensesEuro,),  # noqa: E501
            "refuse_public_allowance_information": (bool,),  # noqa: E501
            "refuse_donation_information": (bool,),  # noqa: E501
            "donation_information_required": (bool,),  # noqa: E501
            "location_of_report_publication": (str,),  # noqa: E501
            "account": (EntryAccount,),  # noqa: E501
            "activity_description": (str,),  # noqa: E501
            "activity_operation_type": (str,),  # noqa: E501
            "activity": (Activity,),  # noqa: E501
            "codex_violation": (bool,),  # noqa: E501
            "lobbyist_identity": (LobbyistIdentity,),  # noqa: E501
            "legislative_projects": ([LegislativeProject],),  # noqa: E501
            "donators": (Donator,),  # noqa: E501
            "fields_of_interest": ([FieldOfInterest],),  # noqa: E501
            "client_organizations": ([ClientOrganization],),  # noqa: E501
            "client_persons": ([NamedEmployee],),  # noqa: E501
            "register_entry_media": ([Media],),  # noqa: E501
            "disclosure_requirements_exist": (bool,),  # noqa: E501
            "refuse_annual_finance_statement": (bool,),  # noqa: E501
            "annual_report_exist": (bool,),  # noqa: E501
            "missing_annual_report_reason": (str,),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None

    attribute_map = {
        "id": "id",  # noqa: E501
        "client_identity": "clientIdentity",  # noqa: E501
        "employee_count": "employeeCount",  # noqa: E501
        "refuse_financial_expenses_information": "refuseFinancialExpensesInformation",  # noqa: E501
        "financial_expenses_euro": "financialExpensesEuro",  # noqa: E501
        "refuse_public_allowance_information": "refusePublicAllowanceInformation",  # noqa: E501
        "refuse_donation_information": "refuseDonationInformation",  # noqa: E501
        "donation_information_required": "donationInformationRequired",  # noqa: E501
        "location_of_report_publication": "locationOfReportPublication",  # noqa: E501
        "account": "account",  # noqa: E501
        "activity_description": "activityDescription",  # noqa: E501
        "activity_operation_type": "activityOperationType",  # noqa: E501
        "activity": "activity",  # noqa: E501
        "codex_violation": "codexViolation",  # noqa: E501
        "lobbyist_identity": "lobbyistIdentity",  # noqa: E501
        "legislative_projects": "legislativeProjects",  # noqa: E501
        "donators": "donators",  # noqa: E501
        "fields_of_interest": "fieldsOfInterest",  # noqa: E501
        "client_organizations": "clientOrganizations",  # noqa: E501
        "client_persons": "clientPersons",  # noqa: E501
        "register_entry_media": "registerEntryMedia",  # noqa: E501
        "disclosure_requirements_exist": "disclosureRequirementsExist",  # noqa: E501
        "refuse_annual_finance_statement": "refuseAnnualFinanceStatement",  # noqa: E501
        "annual_report_exist": "annualReportExist",  # noqa: E501
        "missing_annual_report_reason": "missingAnnualReportReason",  # noqa: E501
    }

    read_only_vars = {}

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, id, *args, **kwargs):  # noqa: E501
        """Entry - a model defined in OpenAPI

        Args:
            id (int):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            client_identity (str): Possible clients this entity is lobbying for.  - `BOTH`: Clients include legal entities and  natural persons - `NATURAL_PERSON`: Clients are only natural persons - `ORGANIZATION`: Clients are only legal entities - `-` There is no client, the entity is lobbying for itself . [optional]  # noqa: E501
            employee_count (EntryEmployeeCount): [optional]  # noqa: E501
            refuse_financial_expenses_information (bool): [optional]  # noqa: E501
            financial_expenses_euro (EntryFinancialExpensesEuro): [optional]  # noqa: E501
            refuse_public_allowance_information (bool): [optional]  # noqa: E501
            refuse_donation_information (bool): [optional]  # noqa: E501
            donation_information_required (bool): True, if this entity received more than € 20,000 of donations from a single donor in the last calendar year . [optional]  # noqa: E501
            location_of_report_publication (str): [optional]  # noqa: E501
            account (EntryAccount): [optional]  # noqa: E501
            activity_description (str): [optional]  # noqa: E501
            activity_operation_type (str): - `MANDATE_OPERATED`: The entity is mandated to lobby for another entity - `SELF_OPERATED`: The entity lobbies for itself - `BOTH`: The entity lobbies for itself and in the mandate of others. . [optional]  # noqa: E501
            activity (Activity): [optional]  # noqa: E501
            codex_violation (bool): [optional]  # noqa: E501
            lobbyist_identity (LobbyistIdentity): [optional]  # noqa: E501
            legislative_projects ([LegislativeProject]): [optional]  # noqa: E501
            donators (Donator): [optional]  # noqa: E501
            fields_of_interest ([FieldOfInterest]): [optional]  # noqa: E501
            client_organizations ([ClientOrganization]): [optional]  # noqa: E501
            client_persons ([NamedEmployee]): [optional]  # noqa: E501
            register_entry_media ([Media]): [optional]  # noqa: E501
            disclosure_requirements_exist (bool): [optional]  # noqa: E501
            refuse_annual_finance_statement (bool): [optional]  # noqa: E501
            annual_report_exist (bool): [optional]  # noqa: E501
            missing_annual_report_reason (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop("_check_type", True)
        _spec_property_naming = kwargs.pop("_spec_property_naming", False)
        _path_to_item = kwargs.pop("_path_to_item", ())
        _configuration = kwargs.pop("_configuration", None)
        _visited_composed_classes = kwargs.pop("_visited_composed_classes", ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments."
                        % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.id = id
        for var_name, var_value in kwargs.items():
            if (
                var_name not in self.attribute_map
                and self._configuration is not None
                and self._configuration.discard_unknown_keys
                and self.additional_properties_type is None
            ):
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set(
        [
            "_data_store",
            "_check_type",
            "_spec_property_naming",
            "_path_to_item",
            "_configuration",
            "_visited_composed_classes",
        ]
    )

    @convert_js_args_to_python_args
    def __init__(self, id, *args, **kwargs):  # noqa: E501
        """Entry - a model defined in OpenAPI

        Args:
            id (int):

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            client_identity (str): Possible clients this entity is lobbying for.  - `BOTH`: Clients include legal entities and  natural persons - `NATURAL_PERSON`: Clients are only natural persons - `ORGANIZATION`: Clients are only legal entities - `-` There is no client, the entity is lobbying for itself . [optional]  # noqa: E501
            employee_count (EntryEmployeeCount): [optional]  # noqa: E501
            refuse_financial_expenses_information (bool): [optional]  # noqa: E501
            financial_expenses_euro (EntryFinancialExpensesEuro): [optional]  # noqa: E501
            refuse_public_allowance_information (bool): [optional]  # noqa: E501
            refuse_donation_information (bool): [optional]  # noqa: E501
            donation_information_required (bool): True, if this entity received more than € 20,000 of donations from a single donor in the last calendar year . [optional]  # noqa: E501
            location_of_report_publication (str): [optional]  # noqa: E501
            account (EntryAccount): [optional]  # noqa: E501
            activity_description (str): [optional]  # noqa: E501
            activity_operation_type (str): - `MANDATE_OPERATED`: The entity is mandated to lobby for another entity - `SELF_OPERATED`: The entity lobbies for itself - `BOTH`: The entity lobbies for itself and in the mandate of others. . [optional]  # noqa: E501
            activity (Activity): [optional]  # noqa: E501
            codex_violation (bool): [optional]  # noqa: E501
            lobbyist_identity (LobbyistIdentity): [optional]  # noqa: E501
            legislative_projects ([LegislativeProject]): [optional]  # noqa: E501
            donators (Donator): [optional]  # noqa: E501
            fields_of_interest ([FieldOfInterest]): [optional]  # noqa: E501
            client_organizations ([ClientOrganization]): [optional]  # noqa: E501
            client_persons ([NamedEmployee]): [optional]  # noqa: E501
            register_entry_media ([Media]): [optional]  # noqa: E501
            disclosure_requirements_exist (bool): [optional]  # noqa: E501
            refuse_annual_finance_statement (bool): [optional]  # noqa: E501
            annual_report_exist (bool): [optional]  # noqa: E501
            missing_annual_report_reason (str): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop("_check_type", True)
        _spec_property_naming = kwargs.pop("_spec_property_naming", False)
        _path_to_item = kwargs.pop("_path_to_item", ())
        _configuration = kwargs.pop("_configuration", None)
        _visited_composed_classes = kwargs.pop("_visited_composed_classes", ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments."
                        % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        self.id = id
        for var_name, var_value in kwargs.items():
            if (
                var_name not in self.attribute_map
                and self._configuration is not None
                and self._configuration.discard_unknown_keys
                and self.additional_properties_type is None
            ):
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(
                    f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                    f"class with read only attributes."
                )
