"""
    Bundestag: Lobbyregister API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.3
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import unittest

from deutschland.bundestag_lobbyregister.api.default_api import DefaultApi  # noqa: E501

from deutschland import bundestag_lobbyregister


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_suche_detail_json(self):
        """Test case for suche_detail_json

        Search through all registrations  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
