"""
    Bundestag: Lobbyregister API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.3
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.bundestag_lobbyregister.model.media_media import MediaMedia

from deutschland import bundestag_lobbyregister

globals()["MediaMedia"] = MediaMedia
from deutschland.bundestag_lobbyregister.model.media import Media


class TestMedia(unittest.TestCase):
    """Media unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMedia(self):
        """Test Media"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Media()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
