"""
    Bundestag: Lobbyregister API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.6
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.bundestag_lobbyregister.model.entry_financial_expenses_euro import (
    EntryFinancialExpensesEuro,
)

from deutschland import bundestag_lobbyregister


class TestEntryFinancialExpensesEuro(unittest.TestCase):
    """EntryFinancialExpensesEuro unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEntryFinancialExpensesEuro(self):
        """Test EntryFinancialExpensesEuro"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EntryFinancialExpensesEuro()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
