"""
    Bundestag: Lobbyregister

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.3
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.bundestag_lobbyregister.model.donator_donation_euro import (
    DonatorDonationEuro,
)

from deutschland import bundestag_lobbyregister

globals()["DonatorDonationEuro"] = DonatorDonationEuro
from deutschland.bundestag_lobbyregister.model.donator import Donator


class TestDonator(unittest.TestCase):
    """Donator unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDonator(self):
        """Test Donator"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Donator()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
