"""
    Bundestag: Lobbyregister API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.6
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.bundestag_lobbyregister.model.number_range import NumberRange

from deutschland import bundestag_lobbyregister


class TestNumberRange(unittest.TestCase):
    """NumberRange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNumberRange(self):
        """Test NumberRange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NumberRange()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
