"""
    Bundestag: Lobbyregister API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.3
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.bundestag_lobbyregister.model.donator_donation_euro import (
    DonatorDonationEuro,
)

from deutschland import bundestag_lobbyregister


class TestDonatorDonationEuro(unittest.TestCase):
    """DonatorDonationEuro unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDonatorDonationEuro(self):
        """Test DonatorDonationEuro"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DonatorDonationEuro()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
