"""
    Bundestag: Lobbyregister API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 1.3
    Contact: kontakt@bund.dev
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

from deutschland.bundestag_lobbyregister.model.sort_order import SortOrder

from deutschland import bundestag_lobbyregister


class TestSortOrder(unittest.TestCase):
    """SortOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSortOrder(self):
        """Test SortOrder"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SortOrder()  # noqa: E501
        pass


if __name__ == "__main__":
    unittest.main()
